### ISSUE TITLE
law rune recipe

### ISSUE THREAD

**Issue by ZeroLyfe** [SelenaQuartzRose/MineScape-Issues#5]
The law rune recipe using enderman essence from magical crops gives end stone instead. Laws can still be crafter using ender pearls though. Another issue I'm having is that I can't use any ranged or magic weapons from wildycraft, bow won't shoot and magic staves won't shoot. I have rune arrows and plenty of runes in my inventory.

**Comment by SelenaQuartzRose** [comment]
Law rune recipe will be fixed in next patch, thanks for your bug report!

As for the magic short bow, I am not sure why but you need to have vanilla arrows on you as well as rune arrows for it to work. I have no idea why that is, but I will make a note of it in the quest for the MSB. 

In fact, the same goes for the staves. I just checked and with just fire runes, the fire staff will not work - but with just fire runes and having arrows in the player's inventory, it does work. 

I have no idea why this is happening, but it doesn't consume the arrows so just keep one in your inventory and you should be good until I track down the source of this issue. Thank you for your issue report.

**Comment by SelenaQuartzRose** [comment]
I found the source of the issue. A dependency library called "Endercore" which is required for "WAILA plugins" is causing the issue. It has a config setting that overrides the default behavior of Bows in Minecraft so that the Infinity Enchantment works without arrows in the inventory, however it is bugged and also causes bows with non-standard ammo to require arrows in the inventory to fire.

I have fixed this for the next patch. Thanks for your bug report!
